# Generated by Django 3.2.9 on 2021-11-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manageusermodels',
            old_name='compañy',
            new_name='company',
        ),
    ]
